#config_version=5
mode:
    start_events: ball_ending     # start on ball ending process
    use_wait_queue: true          # delay ball ending
    priority: 500

mode_settings:
    display_delay_ms: 2s
    hurry_up_delay_ms: 0
    bonus_entries:
      - event: bonus_jet
        score: 10 * current_player.jet_count
      - event: bonus_multip
        score: 10 * current_player.bonus_multiplier 
slide_player:
    mode_bonus_started: bonus_start_slide
    bonus_multip: bonus_multiplier_slide 
    bonus_jet: bonus_jet_slide
    bonus_total: bonus_total_slide
slides:    
  bonus_start_slide:
    widgets:
      - type: text
        text: Bonus  
  bonus_multiplier_slide:
    - type: text
      text: "Multiplier: (bonus_multiplier)X"    
  bonus_jet_slide:
    - type: text
      text: "Bumpers (player|jet_count) : (score)"    
  bonus_total_slide:
    - type: text
      text: "Total Bonus: (score)"    