#config_version=5

config:
- hardware.yaml
- keyboard.yaml
- lights.yaml
- switches.yaml
- variables_player.yaml

displays:
    windows:
        width: 800
        height: 600   
    
modes:
    - base
    - attract

ball_devices:
    bd_trough:
        ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough_jam
        eject_coil: c_trough_eject
        tags: trough, home, drain
        jam_switch: s_trough_jam
        eject_coil_jam_pulse: 15ms
        eject_targets: bd_plunger
        eject_timeouts: 3s        
    bd_plunger:
        ball_switches: s_plunger
        mechanical_eject: true
        eject_targets: playfield
        eject_timeouts: 5s

virtual_platform_start_active_switches: s_trough1, s_trough2, s_trough3, s_trough4