#config_version=5

config:
- hardware.yaml
- shots.yaml

displays:
    windows:
        width: 800
        height: 600   
    
modes:
    - base
    - attract
    - lanechange


ball_devices:
    bd_trough:
        ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough_jam
        eject_coil: c_trough_eject
        tags: trough, home, drain
        jam_switch: s_trough_jam
        eject_coil_jam_pulse: 15ms
        eject_targets: bd_plunger
        eject_timeouts: 3s        
    bd_plunger:
        ball_switches: s_plunger
        mechanical_eject: true
        eject_targets: playfield
        eject_timeouts: 5s

virtual_platform_start_active_switches: s_trough1, s_trough2, s_trough3, s_trough4

keyboard:
    '<':
        switch: s_flipper_left
    ':':
        switch: s_flipper_right
    q:
        switch: s_flipper_upper
    't':
        switch: s_jet_left        
    'y':
        switch: s_jet_right
    'g':
        switch: s_jet_down
    'e':
        switch: s_sling_left
    's':
        switch: s_start
    'd':
        switch: s_right_outlane
    'c':
        switch: s_right_inlane
    'b':
        switch: s_left_inlane
    'a':
        switch: s_left_outlane
    i:
        switch: s_right_inlane
    'm':
        switch: s_slingshot_right
    'f':
        switch: s_left_loop
    'h':
        switch: s_right_loop
    'j':
        switch: s_upper_loop
    p:
        switch: s_plunger
        toggle: true
    1:
        switch: s_trough1
        toggle: true
    2:
        switch: s_trough2
        toggle: true
    3:
        switch: s_trough3
        toggle: true
    4:
        switch: s_trough4
        toggle: true